### ISSUE TITLE
DCMA14 error: print(health.analysis())

### ISSUE THREAD

**Issue by enginance** [HassanEmam/PyP6Xer#9]
Hi, first of all congrats for this awesome project! I just started testing it and I am encountering the following error. Could you please help me figure it out?

Traceback (most recent call last):
  File "c:\Users\neres\VisualStudio Projects\PyP6Xer trial\test_trial.py", line 181, in <module>
    print(health.analysis())
  File "c:\Users\neres\VisualStudio Projects\PyP6Xer trial\xerparser\dcma14\analysis.py", line 97, in analysis
    'cstrs': [self.get_activity(x.task_id) for x in self.constraints]}
  File "c:\Users\neres\VisualStudio Projects\PyP6Xer trial\xerparser\dcma14\analysis.py", line 97, in <listcomp>
    'cstrs': [self.get_activity(x.task_id) for x in self.constraints]}
AttributeError: 'dict' object has no attribute 'task_id'
PS C:\Users\neres\VisualStudio Projects\PyP6Xer trial>

**Comment by HassanEmam** [comment]
Hi @enginance 

Thanks for raising the issue. Would you please provide a sample of the xer file you are trying to analyse and I will have a look at the issue.

**Comment by enginance** [comment]
Hi @HassanEmam ,
thanks for your prompt reply, please find below the sample XER.

[Sample Xer 01.zip](https://github.com/HassanEmam/PyP6Xer/files/8061239/Sample.Xer.01.zip)

**Comment by HassanEmam** [comment]
@enginance 

Thanks for sharing your file. I have ran some tests and found couple of bugs that are now fixed. Try pulling the new code and run the analysis again you should get results.

Below is the output I got from the analysis


`{
	"analysis": {
		"summary": {
			"activity_cnt": 79,
			"relationship_cnt": 110
		},
		"successors": {
			"cnt": 3,
			"activities": [{
				"id": "LH780",
				"name": "Insulation and Built-up Roofing",
				"duration": 10.0,
				"tf": 76.0
			}, {
				"id": "LH899",
				"name": "Finishes Phase Begins",
				"duration": 0.0,
				"tf": 0
			}, {
				"id": "LH970",
				"name": "Building Addition Complete",
				"duration": 0.0,
				"tf": 0
			}],
			"pct": 0.0379746835443038
		},
		"predecessors": {
			"cnt": 1,
			"activities": [{
				"id": "LH400",
				"name": "Design Building Addition",
				"duration": 23.0,
				"tf": 0
			}],
			"pct": 0.012658227848101266
		},
		"lags": {
			"cnt": 11,
			"relations": [{
				"successor": {
					"id": "LH660",
					"name": "Install Underground Water Lines",
					"duration": 5.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH650",
					"name": "Excavation",
					"duration": 10.0,
					"tf": 0
				},
				"type": "PR_SS",
				"lag": 5
			}, {
				"successor": {
					"id": "LH670",
					"name": "Install Storm water lines",
					"duration": 10.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH650",
					"name": "Excavation",
					"duration": 10.0,
					"tf": 0
				},
				"type": "PR_SS",
				"lag": 5
			}, {
				"successor": {
					"id": "LH720",
					"name": "Erect Stairwell and Elevator Walls",
					"duration": 10.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH730",
					"name": "Concrete First Floor",
					"duration": 60.0,
					"tf": 0
				},
				"type": "PR_SS",
				"lag": 5
			}, {
				"successor": {
					"id": "LH770",
					"name": "Install Door and Window Frames",
					"duration": 1.0,
					"tf": 92.0
				},
				"predecessor": {
					"id": "LH755",
					"name": "Brick Exterior Walls",
					"duration": 14.0,
					"tf": 76.0
				},
				"type": "PR_SS",
				"lag": 5
			}, {
				"successor": {
					"id": "LH810",
					"name": "Set Mechanical and Electrical Equipment",
					"duration": 15.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH730",
					"name": "Concrete First Floor",
					"duration": 60.0,
					"tf": 0
				},
				"type": "PR_SS",
				"lag": 7
			}, {
				"successor": {
					"id": "LH840",
					"name": "Rough-In Plumbing/Piping",
					"duration": 45.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH820",
					"name": "Install HVAC Ducts",
					"duration": 25.0,
					"tf": 0
				},
				"type": "PR_SS",
				"lag": 4
			}, {
				"successor": {
					"id": "LH855",
					"name": "Install Wiring and Cable",
					"duration": 45.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH840",
					"name": "Rough-In Plumbing/Piping",
					"duration": 45.0,
					"tf": 0
				},
				"type": "PR_SS",
				"lag": 5
			}, {
				"successor": {
					"id": "LH901",
					"name": "Install Lighting Fixtures",
					"duration": 3.0,
					"tf": 4.0
				},
				"predecessor": {
					"id": "LH900",
					"name": "Install Ceiling Grid",
					"duration": 15.0,
					"tf": 0
				},
				"type": "PR_SS",
				"lag": 8
			}, {
				"successor": {
					"id": "LH902",
					"name": "Install AC Grills and Registers",
					"duration": 5.0,
					"tf": 2.0
				},
				"predecessor": {
					"id": "LH900",
					"name": "Install Ceiling Grid",
					"duration": 15.0,
					"tf": 0
				},
				"type": "PR_SS",
				"lag": 8
			}, {
				"successor": {
					"id": "LH930",
					"name": "Paint Building Interior",
					"duration": 30.0,
					"tf": 3.0
				},
				"predecessor": {
					"id": "LH890",
					"name": "Drywall in Offices",
					"duration": 15.0,
					"tf": 0
				},
				"type": "PR_SS",
				"lag": 7
			}, {
				"successor": {
					"id": "LH755",
					"name": "Brick Exterior Walls",
					"duration": 14.0,
					"tf": 76.0
				},
				"predecessor": {
					"id": "LH735",
					"name": "Concrete Second Floor",
					"duration": 15.0,
					"tf": 0
				},
				"type": "PR_FF",
				"lag": 5
			}],
			"pct": 0.1
		},
		"leads": {
			"cnt": 0,
			"relations": [],
			"pct": 0.0
		},
		"relations": {
			"fs_cnt": 76,
			"relationship": [{
				"successor": {
					"id": "LH469",
					"name": "Assemble Technical Data for Heat Pump",
					"duration": 3.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH501",
					"name": "Review and Approve Designs",
					"duration": 9.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH470",
					"name": "Review Technical Data on Heat Pumps",
					"duration": 8.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH469",
					"name": "Assemble Technical Data for Heat Pump",
					"duration": 3.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH501",
					"name": "Review and Approve Designs",
					"duration": 9.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH400",
					"name": "Design Building Addition",
					"duration": 23.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH469",
					"name": "Assemble Technical Data for Heat Pump",
					"duration": 3.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH400",
					"name": "Design Building Addition",
					"duration": 23.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH407",
					"name": "Prepare and Solicit Bids for Flooring",
					"duration": 5.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH560",
					"name": "Review and Approve Flooring",
					"duration": 10.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH408",
					"name": "Review Bids for Flooring",
					"duration": 3.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH407",
					"name": "Prepare and Solicit Bids for Flooring",
					"duration": 5.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH409",
					"name": "Award Contract for Flooring",
					"duration": 1.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH408",
					"name": "Review Bids for Flooring",
					"duration": 3.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH411",
					"name": "Prepare and Solicit Bids for Heat Pump",
					"duration": 10.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH470",
					"name": "Review Technical Data on Heat Pumps",
					"duration": 8.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH412",
					"name": "Review Bids for Heat Pump",
					"duration": 2.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH411",
					"name": "Prepare and Solicit Bids for Heat Pump",
					"duration": 10.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH413",
					"name": "Award Contract for Heat Pump",
					"duration": 10.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH412",
					"name": "Review Bids for Heat Pump",
					"duration": 2.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH421",
					"name": "Review Bids",
					"duration": 10.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH530",
					"name": "Review and Approve Brick Samples",
					"duration": 183.0,
					"tf": 76.0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH422",
					"name": "Review Bids for Brick",
					"duration": 3.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH421",
					"name": "Review Bids",
					"duration": 10.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH423",
					"name": "Award Contract for Brick",
					"duration": 2.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH422",
					"name": "Review Bids for Brick",
					"duration": 3.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH450",
					"name": "Assemble Brick Samples",
					"duration": 3.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH501",
					"name": "Review and Approve Designs",
					"duration": 9.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH480",
					"name": "Assemble and Submit Flooring Samples",
					"duration": 8.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH501",
					"name": "Review and Approve Designs",
					"duration": 9.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH530",
					"name": "Review and Approve Brick Samples",
					"duration": 183.0,
					"tf": 76.0
				},
				"predecessor": {
					"id": "LH450",
					"name": "Assemble Brick Samples",
					"duration": 3.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH550",
					"name": "Fabricate and Deliver Heat Pump and Controls",
					"duration": 88.0,
					"tf": 97.0
				},
				"predecessor": {
					"id": "LH413",
					"name": "Award Contract for Heat Pump",
					"duration": 10.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH560",
					"name": "Review and Approve Flooring",
					"duration": 10.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH480",
					"name": "Assemble and Submit Flooring Samples",
					"duration": 8.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH600",
					"name": "Deliver Brick",
					"duration": 58.0,
					"tf": 159.0
				},
				"predecessor": {
					"id": "LH423",
					"name": "Award Contract for Brick",
					"duration": 2.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH620",
					"name": "Fabricate and Deliver Flooring",
					"duration": 58.0,
					"tf": 172.0
				},
				"predecessor": {
					"id": "LH409",
					"name": "Award Contract for Flooring",
					"duration": 1.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH630",
					"name": "Begin Building Construction",
					"duration": 0.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH501",
					"name": "Review and Approve Designs",
					"duration": 9.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH650",
					"name": "Excavation",
					"duration": 10.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH640",
					"name": "Site Preparation",
					"duration": 10.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH680",
					"name": "Form/Pour Concrete Footings",
					"duration": 10.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH660",
					"name": "Install Underground Water Lines",
					"duration": 5.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH680",
					"name": "Form/Pour Concrete Footings",
					"duration": 10.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH670",
					"name": "Install Storm water lines",
					"duration": 10.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH681",
					"name": "Concrete Foundation Walls",
					"duration": 14.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH680",
					"name": "Form/Pour Concrete Footings",
					"duration": 10.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH690",
					"name": "Form and Pour Slab",
					"duration": 10.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH681",
					"name": "Concrete Foundation Walls",
					"duration": 14.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH700",
					"name": "Backfill and Compact Walls",
					"duration": 5.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH690",
					"name": "Form and Pour Slab",
					"duration": 10.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH701",
					"name": "Foundation Phase Complete",
					"duration": 0.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH700",
					"name": "Backfill and Compact Walls",
					"duration": 5.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH702",
					"name": "Begin Structural Phase",
					"duration": 0.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH710",
					"name": "Erect Structural Frame",
					"duration": 34.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH710",
					"name": "Erect Structural Frame",
					"duration": 34.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH700",
					"name": "Backfill and Compact Walls",
					"duration": 5.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH712",
					"name": "Floor Decking",
					"duration": 28.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH710",
					"name": "Erect Structural Frame",
					"duration": 34.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH730",
					"name": "Concrete First Floor",
					"duration": 60.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH712",
					"name": "Floor Decking",
					"duration": 28.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH731",
					"name": "Concrete Basement Slab",
					"duration": 15.0,
					"tf": 76.0
				},
				"predecessor": {
					"id": "LH730",
					"name": "Concrete First Floor",
					"duration": 60.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH755",
					"name": "Brick Exterior Walls",
					"duration": 14.0,
					"tf": 76.0
				},
				"predecessor": {
					"id": "LH600",
					"name": "Deliver Brick",
					"duration": 58.0,
					"tf": 159.0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH780",
					"name": "Insulation and Built-up Roofing",
					"duration": 10.0,
					"tf": 76.0
				},
				"predecessor": {
					"id": "LH755",
					"name": "Brick Exterior Walls",
					"duration": 14.0,
					"tf": 76.0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH790",
					"name": "Install Exterior Doors and Windows",
					"duration": 2.0,
					"tf": 92.0
				},
				"predecessor": {
					"id": "LH770",
					"name": "Install Door and Window Frames",
					"duration": 1.0,
					"tf": 92.0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH809",
					"name": "Rough-In Phase Begins",
					"duration": 0.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH810",
					"name": "Set Mechanical and Electrical Equipment",
					"duration": 15.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH820",
					"name": "Install HVAC Ducts",
					"duration": 25.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH810",
					"name": "Set Mechanical and Electrical Equipment",
					"duration": 15.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH830",
					"name": "Insulate Ducts",
					"duration": 2.0,
					"tf": 22.0
				},
				"predecessor": {
					"id": "LH820",
					"name": "Install HVAC Ducts",
					"duration": 25.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH831",
					"name": "Set Heat Pump",
					"duration": 5.0,
					"tf": 22.0
				},
				"predecessor": {
					"id": "LH550",
					"name": "Fabricate and Deliver Heat Pump and Controls",
					"duration": 88.0,
					"tf": 97.0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH831",
					"name": "Set Heat Pump",
					"duration": 5.0,
					"tf": 22.0
				},
				"predecessor": {
					"id": "LH830",
					"name": "Insulate Ducts",
					"duration": 2.0,
					"tf": 22.0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH860",
					"name": "Install Elevator Rails and Equipment",
					"duration": 40.0,
					"tf": -78.0
				},
				"predecessor": {
					"id": "LH720",
					"name": "Erect Stairwell and Elevator Walls",
					"duration": 10.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH870",
					"name": "Connect Equipment",
					"duration": 3.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH831",
					"name": "Set Heat Pump",
					"duration": 5.0,
					"tf": 22.0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH870",
					"name": "Connect Equipment",
					"duration": 3.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH855",
					"name": "Install Wiring and Cable",
					"duration": 45.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH871",
					"name": "Startup and Test HVAC",
					"duration": 1.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH870",
					"name": "Connect Equipment",
					"duration": 3.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH880",
					"name": "Rough In Complete",
					"duration": 0.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH860",
					"name": "Install Elevator Rails and Equipment",
					"duration": 40.0,
					"tf": -78.0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH880",
					"name": "Rough In Complete",
					"duration": 0.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH871",
					"name": "Startup and Test HVAC",
					"duration": 1.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH890",
					"name": "Drywall in Offices",
					"duration": 15.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH880",
					"name": "Rough In Complete",
					"duration": 0.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH899",
					"name": "Finishes Phase Begins",
					"duration": 0.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH890",
					"name": "Drywall in Offices",
					"duration": 15.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH900",
					"name": "Install Ceiling Grid",
					"duration": 15.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH890",
					"name": "Drywall in Offices",
					"duration": 15.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH910",
					"name": "Install Floor and Carpeting",
					"duration": 5.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH620",
					"name": "Fabricate and Deliver Flooring",
					"duration": 58.0,
					"tf": 172.0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH910",
					"name": "Install Floor and Carpeting",
					"duration": 5.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH900",
					"name": "Install Ceiling Grid",
					"duration": 15.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH910",
					"name": "Install Floor and Carpeting",
					"duration": 5.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH901",
					"name": "Install Lighting Fixtures",
					"duration": 3.0,
					"tf": 4.0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH910",
					"name": "Install Floor and Carpeting",
					"duration": 5.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH902",
					"name": "Install AC Grills and Registers",
					"duration": 5.0,
					"tf": 2.0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH911",
					"name": "Finish Carpentry and Millwork",
					"duration": 5.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH910",
					"name": "Install Floor and Carpeting",
					"duration": 5.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH912",
					"name": "Install Plumbing Fixtures",
					"duration": 2.0,
					"tf": 3.0
				},
				"predecessor": {
					"id": "LH910",
					"name": "Install Floor and Carpeting",
					"duration": 5.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH913",
					"name": "Install Elevator Cab and Finishes",
					"duration": 20.0,
					"tf": 20.0
				},
				"predecessor": {
					"id": "LH880",
					"name": "Rough In Complete",
					"duration": 0.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH940",
					"name": "Touch-up and Clean-up",
					"duration": 1.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH911",
					"name": "Finish Carpentry and Millwork",
					"duration": 5.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH940",
					"name": "Touch-up and Clean-up",
					"duration": 1.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH912",
					"name": "Install Plumbing Fixtures",
					"duration": 2.0,
					"tf": 3.0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH940",
					"name": "Touch-up and Clean-up",
					"duration": 1.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH913",
					"name": "Install Elevator Cab and Finishes",
					"duration": 20.0,
					"tf": 20.0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH940",
					"name": "Touch-up and Clean-up",
					"duration": 1.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH930",
					"name": "Paint Building Interior",
					"duration": 30.0,
					"tf": 3.0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH941",
					"name": "Test and Balance HVAC Equipment",
					"duration": 1.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH940",
					"name": "Touch-up and Clean-up",
					"duration": 1.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH950",
					"name": "Finishes Milestone",
					"duration": 0.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH941",
					"name": "Test and Balance HVAC Equipment",
					"duration": 1.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH960",
					"name": "Punch List",
					"duration": 2.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH950",
					"name": "Finishes Milestone",
					"duration": 0.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH970",
					"name": "Building Addition Complete",
					"duration": 0.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH960",
					"name": "Punch List",
					"duration": 2.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH983",
					"name": "Relocate HVAC Chiller",
					"duration": 3.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH831",
					"name": "Set Heat Pump",
					"duration": 5.0,
					"tf": 22.0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH871",
					"name": "Startup and Test HVAC",
					"duration": 1.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH983",
					"name": "Relocate HVAC Chiller",
					"duration": 3.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH735",
					"name": "Concrete Second Floor",
					"duration": 15.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH730",
					"name": "Concrete First Floor",
					"duration": 60.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH710",
					"name": "Erect Structural Frame",
					"duration": 34.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH701",
					"name": "Foundation Phase Complete",
					"duration": 0.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH755",
					"name": "Brick Exterior Walls",
					"duration": 14.0,
					"tf": 76.0
				},
				"predecessor": {
					"id": "LH730",
					"name": "Concrete First Floor",
					"duration": 60.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH780",
					"name": "Insulation and Built-up Roofing",
					"duration": 10.0,
					"tf": 76.0
				},
				"predecessor": {
					"id": "LH735",
					"name": "Concrete Second Floor",
					"duration": 15.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH712",
					"name": "Floor Decking",
					"duration": 28.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH702",
					"name": "Begin Structural Phase",
					"duration": 0.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH490",
					"name": "Site work I",
					"duration": 50.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH630",
					"name": "Begin Building Construction",
					"duration": 0.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH510",
					"name": "Site work II",
					"duration": 45.0,
					"tf": 74.0
				},
				"predecessor": {
					"id": "LH490",
					"name": "Site work I",
					"duration": 50.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH820",
					"name": "Install HVAC Ducts",
					"duration": 25.0,
					"tf": 0
				},
				"predecessor": {
					"id": "LH735",
					"name": "Concrete Second Floor",
					"duration": 15.0,
					"tf": 0
				},
				"type": "PR_FS",
				"lag": 0
			}, {
				"successor": {
					"id": "LH755",
					"name": "Brick Exterior Walls",
					"duration": 14.0,
					"tf": 76.0
				},
				"predecessor": {
					"id": "LH731",
					"name": "Concrete Basement Slab",
					"duration": 15.0,
					"tf": 76.0
				},
				"type": "PR_FS",
				"lag": 0
			}]
		},
		"constraints": {
			"cstr_cnt": 0,
			"cstrs": []
		},
		"totalfloat": {
			"cnt": 17,
			"activities": [{
				"id": "LH530",
				"name": "Review and Approve Brick Samples",
				"duration": 183.0,
				"tf": 76.0
			}, {
				"id": "LH550",
				"name": "Fabricate and Deliver Heat Pump and Controls",
				"duration": 88.0,
				"tf": 97.0
			}, {
				"id": "LH600",
				"name": "Deliver Brick",
				"duration": 58.0,
				"tf": 159.0
			}, {
				"id": "LH620",
				"name": "Fabricate and Deliver Flooring",
				"duration": 58.0,
				"tf": 172.0
			}, {
				"id": "LH731",
				"name": "Concrete Basement Slab",
				"duration": 15.0,
				"tf": 76.0
			}, {
				"id": "LH755",
				"name": "Brick Exterior Walls",
				"duration": 14.0,
				"tf": 76.0
			}, {
				"id": "LH770",
				"name": "Install Door and Window Frames",
				"duration": 1.0,
				"tf": 92.0
			}, {
				"id": "LH780",
				"name": "Insulation and Built-up Roofing",
				"duration": 10.0,
				"tf": 76.0
			}, {
				"id": "LH790",
				"name": "Install Exterior Doors and Windows",
				"duration": 2.0,
				"tf": 92.0
			}, {
				"id": "LH830",
				"name": "Insulate Ducts",
				"duration": 2.0,
				"tf": 22.0
			}, {
				"id": "LH831",
				"name": "Set Heat Pump",
				"duration": 5.0,
				"tf": 22.0
			}, {
				"id": "LH901",
				"name": "Install Lighting Fixtures",
				"duration": 3.0,
				"tf": 4.0
			}, {
				"id": "LH902",
				"name": "Install AC Grills and Registers",
				"duration": 5.0,
				"tf": 2.0
			}, {
				"id": "LH912",
				"name": "Install Plumbing Fixtures",
				"duration": 2.0,
				"tf": 3.0
			}, {
				"id": "LH913",
				"name": "Install Elevator Cab and Finishes",
				"duration": 20.0,
				"tf": 20.0
			}, {
				"id": "LH930",
				"name": "Paint Building Interior",
				"duration": 30.0,
				"tf": 3.0
			}, {
				"id": "LH510",
				"name": "Site work II",
				"duration": 45.0,
				"tf": 74.0
			}],
			"pct": 0.21518987341772153
		},
		"negativefloat": {
			"cnt": 5,
			"activities": [{
				"id": "LH555",
				"name": "Foundation",
				"duration": 64.0,
				"tf": -53.0
			}, {
				"id": "LH750",
				"name": "Elevator",
				"duration": 60.0,
				"tf": -78.0
			}, {
				"id": "LH860",
				"name": "Install Elevator Rails and Equipment",
				"duration": 40.0,
				"tf": -78.0
			}, {
				"id": "LH655",
				"name": "Exterior Finish Costs",
				"duration": 205.0,
				"tf": -27.0
			}, {
				"id": "LH500",
				"name": "Sitework",
				"duration": 95.0,
				"tf": -53.0
			}],
			"pct": 0.06329113924050633
		},
		"duration": {
			"cnt": 66,
			"activities": [{
				"id": "LH400",
				"name": "Design Building Addition",
				"duration": 23.0,
				"tf": 0
			}, {
				"id": "LH469",
				"name": "Assemble Technical Data for Heat Pump",
				"duration": 3.0,
				"tf": 0
			}, {
				"id": "LH470",
				"name": "Review Technical Data on Heat Pumps",
				"duration": 8.0,
				"tf": 0
			}, {
				"id": "LH501",
				"name": "Review and Approve Designs",
				"duration": 9.0,
				"tf": 0
			}, {
				"id": "LH455",
				"name": "Design",
				"duration": 43.0,
				"tf": 0
			}, {
				"id": "LH555",
				"name": "Foundation",
				"duration": 64.0,
				"tf": -53.0
			}, {
				"id": "LH605",
				"name": "Structure",
				"duration": 103.0,
				"tf": 0
			}, {
				"id": "LH750",
				"name": "Elevator",
				"duration": 60.0,
				"tf": -78.0
			}, {
				"id": "LH407",
				"name": "Prepare and Solicit Bids for Flooring",
				"duration": 5.0,
				"tf": 0
			}, {
				"id": "LH408",
				"name": "Review Bids for Flooring",
				"duration": 3.0,
				"tf": 0
			}, {
				"id": "LH411",
				"name": "Prepare and Solicit Bids for Heat Pump",
				"duration": 10.0,
				"tf": 0
			}, {
				"id": "LH412",
				"name": "Review Bids for Heat Pump",
				"duration": 2.0,
				"tf": 0
			}, {
				"id": "LH413",
				"name": "Award Contract for Heat Pump",
				"duration": 10.0,
				"tf": 0
			}, {
				"id": "LH421",
				"name": "Review Bids",
				"duration": 10.0,
				"tf": 0
			}, {
				"id": "LH422",
				"name": "Review Bids for Brick",
				"duration": 3.0,
				"tf": 0
			}, {
				"id": "LH423",
				"name": "Award Contract for Brick",
				"duration": 2.0,
				"tf": 0
			}, {
				"id": "LH450",
				"name": "Assemble Brick Samples",
				"duration": 3.0,
				"tf": 0
			}, {
				"id": "LH480",
				"name": "Assemble and Submit Flooring Samples",
				"duration": 8.0,
				"tf": 0
			}, {
				"id": "LH530",
				"name": "Review and Approve Brick Samples",
				"duration": 183.0,
				"tf": 76.0
			}, {
				"id": "LH550",
				"name": "Fabricate and Deliver Heat Pump and Controls",
				"duration": 88.0,
				"tf": 97.0
			}, {
				"id": "LH560",
				"name": "Review and Approve Flooring",
				"duration": 10.0,
				"tf": 0
			}, {
				"id": "LH600",
				"name": "Deliver Brick",
				"duration": 58.0,
				"tf": 159.0
			}, {
				"id": "LH620",
				"name": "Fabricate and Deliver Flooring",
				"duration": 58.0,
				"tf": 172.0
			}, {
				"id": "LH640",
				"name": "Site Preparation",
				"duration": 10.0,
				"tf": 0
			}, {
				"id": "LH650",
				"name": "Excavation",
				"duration": 10.0,
				"tf": 0
			}, {
				"id": "LH660",
				"name": "Install Underground Water Lines",
				"duration": 5.0,
				"tf": 0
			}, {
				"id": "LH670",
				"name": "Install Storm water lines",
				"duration": 10.0,
				"tf": 0
			}, {
				"id": "LH680",
				"name": "Form/Pour Concrete Footings",
				"duration": 10.0,
				"tf": 0
			}, {
				"id": "LH681",
				"name": "Concrete Foundation Walls",
				"duration": 14.0,
				"tf": 0
			}, {
				"id": "LH690",
				"name": "Form and Pour Slab",
				"duration": 10.0,
				"tf": 0
			}, {
				"id": "LH700",
				"name": "Backfill and Compact Walls",
				"duration": 5.0,
				"tf": 0
			}, {
				"id": "LH710",
				"name": "Erect Structural Frame",
				"duration": 34.0,
				"tf": 0
			}, {
				"id": "LH712",
				"name": "Floor Decking",
				"duration": 28.0,
				"tf": 0
			}, {
				"id": "LH720",
				"name": "Erect Stairwell and Elevator Walls",
				"duration": 10.0,
				"tf": 0
			}, {
				"id": "LH730",
				"name": "Concrete First Floor",
				"duration": 60.0,
				"tf": 0
			}, {
				"id": "LH731",
				"name": "Concrete Basement Slab",
				"duration": 15.0,
				"tf": 76.0
			}, {
				"id": "LH755",
				"name": "Brick Exterior Walls",
				"duration": 14.0,
				"tf": 76.0
			}, {
				"id": "LH780",
				"name": "Insulation and Built-up Roofing",
				"duration": 10.0,
				"tf": 76.0
			}, {
				"id": "LH790",
				"name": "Install Exterior Doors and Windows",
				"duration": 2.0,
				"tf": 92.0
			}, {
				"id": "LH810",
				"name": "Set Mechanical and Electrical Equipment",
				"duration": 15.0,
				"tf": 0
			}, {
				"id": "LH820",
				"name": "Install HVAC Ducts",
				"duration": 25.0,
				"tf": 0
			}, {
				"id": "LH830",
				"name": "Insulate Ducts",
				"duration": 2.0,
				"tf": 22.0
			}, {
				"id": "LH831",
				"name": "Set Heat Pump",
				"duration": 5.0,
				"tf": 22.0
			}, {
				"id": "LH840",
				"name": "Rough-In Plumbing/Piping",
				"duration": 45.0,
				"tf": 0
			}, {
				"id": "LH855",
				"name": "Install Wiring and Cable",
				"duration": 45.0,
				"tf": 0
			}, {
				"id": "LH860",
				"name": "Install Elevator Rails and Equipment",
				"duration": 40.0,
				"tf": -78.0
			}, {
				"id": "LH870",
				"name": "Connect Equipment",
				"duration": 3.0,
				"tf": 0
			}, {
				"id": "LH890",
				"name": "Drywall in Offices",
				"duration": 15.0,
				"tf": 0
			}, {
				"id": "LH900",
				"name": "Install Ceiling Grid",
				"duration": 15.0,
				"tf": 0
			}, {
				"id": "LH901",
				"name": "Install Lighting Fixtures",
				"duration": 3.0,
				"tf": 4.0
			}, {
				"id": "LH902",
				"name": "Install AC Grills and Registers",
				"duration": 5.0,
				"tf": 2.0
			}, {
				"id": "LH910",
				"name": "Install Floor and Carpeting",
				"duration": 5.0,
				"tf": 0
			}, {
				"id": "LH911",
				"name": "Finish Carpentry and Millwork",
				"duration": 5.0,
				"tf": 0
			}, {
				"id": "LH912",
				"name": "Install Plumbing Fixtures",
				"duration": 2.0,
				"tf": 3.0
			}, {
				"id": "LH913",
				"name": "Install Elevator Cab and Finishes",
				"duration": 20.0,
				"tf": 20.0
			}, {
				"id": "LH930",
				"name": "Paint Building Interior",
				"duration": 30.0,
				"tf": 3.0
			}, {
				"id": "LH960",
				"name": "Punch List",
				"duration": 2.0,
				"tf": 0
			}, {
				"id": "LH735",
				"name": "Concrete Second Floor",
				"duration": 15.0,
				"tf": 0
			}, {
				"id": "LH983",
				"name": "Relocate HVAC Chiller",
				"duration": 3.0,
				"tf": 0
			}, {
				"id": "LH800",
				"name": "HVAC, Plumbing & Fire Protection",
				"duration": 115.0,
				"tf": 0
			}, {
				"id": "LH850",
				"name": "Electrical Costs",
				"duration": 152.0,
				"tf": 0
			}, {
				"id": "LH655",
				"name": "Exterior Finish Costs",
				"duration": 205.0,
				"tf": -27.0
			}, {
				"id": "LH705",
				"name": "Interior Finish Costs",
				"duration": 64.0,
				"tf": 0
			}, {
				"id": "LH490",
				"name": "Site work I",
				"duration": 50.0,
				"tf": 0
			}, {
				"id": "LH500",
				"name": "Sitework",
				"duration": 95.0,
				"tf": -53.0
			}, {
				"id": "LH510",
				"name": "Site work II",
				"duration": 45.0,
				"tf": 74.0
			}],
			"pct": 0.8354430379746836
		},
		"invaliddates": {
			"actual_start": [{
				"id": "LH701",
				"name": "Foundation Phase Complete",
				"duration": 0.0,
				"tf": 0
			}, {
				"id": "LH702",
				"name": "Begin Structural Phase",
				"duration": 0.0,
				"tf": 0
			}, {
				"id": "LH710",
				"name": "Erect Structural Frame",
				"duration": 34.0,
				"tf": 0
			}, {
				"id": "LH809",
				"name": "Rough-In Phase Begins",
				"duration": 0.0,
				"tf": 0
			}, {
				"id": "LH880",
				"name": "Rough In Complete",
				"duration": 0.0,
				"tf": 0
			}, {
				"id": "LH899",
				"name": "Finishes Phase Begins",
				"duration": 0.0,
				"tf": 0
			}, {
				"id": "LH950",
				"name": "Finishes Milestone",
				"duration": 0.0,
				"tf": 0
			}, {
				"id": "LH960",
				"name": "Punch List",
				"duration": 2.0,
				"tf": 0
			}, {
				"id": "LH970",
				"name": "Building Addition Complete",
				"duration": 0.0,
				"tf": 0
			}],
			"actual_finish": [{
				"id": "LH701",
				"name": "Foundation Phase Complete",
				"duration": 0.0,
				"tf": 0
			}, {
				"id": "LH702",
				"name": "Begin Structural Phase",
				"duration": 0.0,
				"tf": 0
			}, {
				"id": "LH710",
				"name": "Erect Structural Frame",
				"duration": 34.0,
				"tf": 0
			}, {
				"id": "LH809",
				"name": "Rough-In Phase Begins",
				"duration": 0.0,
				"tf": 0
			}, {
				"id": "LH880",
				"name": "Rough In Complete",
				"duration": 0.0,
				"tf": 0
			}, {
				"id": "LH899",
				"name": "Finishes Phase Begins",
				"duration": 0.0,
				"tf": 0
			}, {
				"id": "LH950",
				"name": "Finishes Milestone",
				"duration": 0.0,
				"tf": 0
			}, {
				"id": "LH960",
				"name": "Punch List",
				"duration": 2.0,
				"tf": 0
			}, {
				"id": "LH970",
				"name": "Building Addition Complete",
				"duration": 0.0,
				"tf": 0
			}],
			"early_start": [],
			"early_finish": [],
			"cnt": 18,
			"pct": 0.22784810126582278
		},
		"resources": {
			"activities": [{
				"id": "LH400",
				"name": "Design Building Addition",
				"duration": 23.0,
				"tf": 0
			}, {
				"id": "LH470",
				"name": "Review Technical Data on Heat Pumps",
				"duration": 8.0,
				"tf": 0
			}, {
				"id": "LH501",
				"name": "Review and Approve Designs",
				"duration": 9.0,
				"tf": 0
			}, {
				"id": "LH455",
				"name": "Design",
				"duration": 43.0,
				"tf": 0
			}, {
				"id": "LH555",
				"name": "Foundation",
				"duration": 64.0,
				"tf": -53.0
			}, {
				"id": "LH605",
				"name": "Structure",
				"duration": 103.0,
				"tf": 0
			}, {
				"id": "LH750",
				"name": "Elevator",
				"duration": 60.0,
				"tf": -78.0
			}, {
				"id": "LH407",
				"name": "Prepare and Solicit Bids for Flooring",
				"duration": 5.0,
				"tf": 0
			}, {
				"id": "LH408",
				"name": "Review Bids for Flooring",
				"duration": 3.0,
				"tf": 0
			}, {
				"id": "LH409",
				"name": "Award Contract for Flooring",
				"duration": 1.0,
				"tf": 0
			}, {
				"id": "LH411",
				"name": "Prepare and Solicit Bids for Heat Pump",
				"duration": 10.0,
				"tf": 0
			}, {
				"id": "LH412",
				"name": "Review Bids for Heat Pump",
				"duration": 2.0,
				"tf": 0
			}, {
				"id": "LH413",
				"name": "Award Contract for Heat Pump",
				"duration": 10.0,
				"tf": 0
			}, {
				"id": "LH421",
				"name": "Review Bids",
				"duration": 10.0,
				"tf": 0
			}, {
				"id": "LH422",
				"name": "Review Bids for Brick",
				"duration": 3.0,
				"tf": 0
			}, {
				"id": "LH423",
				"name": "Award Contract for Brick",
				"duration": 2.0,
				"tf": 0
			}, {
				"id": "LH450",
				"name": "Assemble Brick Samples",
				"duration": 3.0,
				"tf": 0
			}, {
				"id": "LH480",
				"name": "Assemble and Submit Flooring Samples",
				"duration": 8.0,
				"tf": 0
			}, {
				"id": "LH530",
				"name": "Review and Approve Brick Samples",
				"duration": 183.0,
				"tf": 76.0
			}, {
				"id": "LH550",
				"name": "Fabricate and Deliver Heat Pump and Controls",
				"duration": 88.0,
				"tf": 97.0
			}, {
				"id": "LH560",
				"name": "Review and Approve Flooring",
				"duration": 10.0,
				"tf": 0
			}, {
				"id": "LH600",
				"name": "Deliver Brick",
				"duration": 58.0,
				"tf": 159.0
			}, {
				"id": "LH620",
				"name": "Fabricate and Deliver Flooring",
				"duration": 58.0,
				"tf": 172.0
			}, {
				"id": "LH630",
				"name": "Begin Building Construction",
				"duration": 0.0,
				"tf": 0
			}, {
				"id": "LH640",
				"name": "Site Preparation",
				"duration": 10.0,
				"tf": 0
			}, {
				"id": "LH650",
				"name": "Excavation",
				"duration": 10.0,
				"tf": 0
			}, {
				"id": "LH660",
				"name": "Install Underground Water Lines",
				"duration": 5.0,
				"tf": 0
			}, {
				"id": "LH670",
				"name": "Install Storm water lines",
				"duration": 10.0,
				"tf": 0
			}, {
				"id": "LH680",
				"name": "Form/Pour Concrete Footings",
				"duration": 10.0,
				"tf": 0
			}, {
				"id": "LH681",
				"name": "Concrete Foundation Walls",
				"duration": 14.0,
				"tf": 0
			}, {
				"id": "LH690",
				"name": "Form and Pour Slab",
				"duration": 10.0,
				"tf": 0
			}, {
				"id": "LH700",
				"name": "Backfill and Compact Walls",
				"duration": 5.0,
				"tf": 0
			}, {
				"id": "LH701",
				"name": "Foundation Phase Complete",
				"duration": 0.0,
				"tf": 0
			}, {
				"id": "LH702",
				"name": "Begin Structural Phase",
				"duration": 0.0,
				"tf": 0
			}, {
				"id": "LH710",
				"name": "Erect Structural Frame",
				"duration": 34.0,
				"tf": 0
			}, {
				"id": "LH712",
				"name": "Floor Decking",
				"duration": 28.0,
				"tf": 0
			}, {
				"id": "LH720",
				"name": "Erect Stairwell and Elevator Walls",
				"duration": 10.0,
				"tf": 0
			}, {
				"id": "LH730",
				"name": "Concrete First Floor",
				"duration": 60.0,
				"tf": 0
			}, {
				"id": "LH731",
				"name": "Concrete Basement Slab",
				"duration": 15.0,
				"tf": 76.0
			}, {
				"id": "LH755",
				"name": "Brick Exterior Walls",
				"duration": 14.0,
				"tf": 76.0
			}, {
				"id": "LH770",
				"name": "Install Door and Window Frames",
				"duration": 1.0,
				"tf": 92.0
			}, {
				"id": "LH780",
				"name": "Insulation and Built-up Roofing",
				"duration": 10.0,
				"tf": 76.0
			}, {
				"id": "LH790",
				"name": "Install Exterior Doors and Windows",
				"duration": 2.0,
				"tf": 92.0
			}, {
				"id": "LH809",
				"name": "Rough-In Phase Begins",
				"duration": 0.0,
				"tf": 0
			}, {
				"id": "LH810",
				"name": "Set Mechanical and Electrical Equipment",
				"duration": 15.0,
				"tf": 0
			}, {
				"id": "LH820",
				"name": "Install HVAC Ducts",
				"duration": 25.0,
				"tf": 0
			}, {
				"id": "LH830",
				"name": "Insulate Ducts",
				"duration": 2.0,
				"tf": 22.0
			}, {
				"id": "LH831",
				"name": "Set Heat Pump",
				"duration": 5.0,
				"tf": 22.0
			}, {
				"id": "LH840",
				"name": "Rough-In Plumbing/Piping",
				"duration": 45.0,
				"tf": 0
			}, {
				"id": "LH855",
				"name": "Install Wiring and Cable",
				"duration": 45.0,
				"tf": 0
			}, {
				"id": "LH860",
				"name": "Install Elevator Rails and Equipment",
				"duration": 40.0,
				"tf": -78.0
			}, {
				"id": "LH870",
				"name": "Connect Equipment",
				"duration": 3.0,
				"tf": 0
			}, {
				"id": "LH871",
				"name": "Startup and Test HVAC",
				"duration": 1.0,
				"tf": 0
			}, {
				"id": "LH880",
				"name": "Rough In Complete",
				"duration": 0.0,
				"tf": 0
			}, {
				"id": "LH890",
				"name": "Drywall in Offices",
				"duration": 15.0,
				"tf": 0
			}, {
				"id": "LH899",
				"name": "Finishes Phase Begins",
				"duration": 0.0,
				"tf": 0
			}, {
				"id": "LH900",
				"name": "Install Ceiling Grid",
				"duration": 15.0,
				"tf": 0
			}, {
				"id": "LH901",
				"name": "Install Lighting Fixtures",
				"duration": 3.0,
				"tf": 4.0
			}, {
				"id": "LH902",
				"name": "Install AC Grills and Registers",
				"duration": 5.0,
				"tf": 2.0
			}, {
				"id": "LH910",
				"name": "Install Floor and Carpeting",
				"duration": 5.0,
				"tf": 0
			}, {
				"id": "LH911",
				"name": "Finish Carpentry and Millwork",
				"duration": 5.0,
				"tf": 0
			}, {
				"id": "LH912",
				"name": "Install Plumbing Fixtures",
				"duration": 2.0,
				"tf": 3.0
			}, {
				"id": "LH913",
				"name": "Install Elevator Cab and Finishes",
				"duration": 20.0,
				"tf": 20.0
			}, {
				"id": "LH930",
				"name": "Paint Building Interior",
				"duration": 30.0,
				"tf": 3.0
			}, {
				"id": "LH940",
				"name": "Touch-up and Clean-up",
				"duration": 1.0,
				"tf": 0
			}, {
				"id": "LH941",
				"name": "Test and Balance HVAC Equipment",
				"duration": 1.0,
				"tf": 0
			}, {
				"id": "LH950",
				"name": "Finishes Milestone",
				"duration": 0.0,
				"tf": 0
			}, {
				"id": "LH960",
				"name": "Punch List",
				"duration": 2.0,
				"tf": 0
			}, {
				"id": "LH970",
				"name": "Building Addition Complete",
				"duration": 0.0,
				"tf": 0
			}, {
				"id": "LH735",
				"name": "Concrete Second Floor",
				"duration": 15.0,
				"tf": 0
			}, {
				"id": "LH983",
				"name": "Relocate HVAC Chiller",
				"duration": 3.0,
				"tf": 0
			}, {
				"id": "LH800",
				"name": "HVAC, Plumbing & Fire Protection",
				"duration": 115.0,
				"tf": 0
			}, {
				"id": "LH850",
				"name": "Electrical Costs",
				"duration": 152.0,
				"tf": 0
			}, {
				"id": "LH655",
				"name": "Exterior Finish Costs",
				"duration": 205.0,
				"tf": -27.0
			}, {
				"id": "LH705",
				"name": "Interior Finish Costs",
				"duration": 64.0,
				"tf": 0
			}, {
				"id": "LH490",
				"name": "Site work I",
				"duration": 50.0,
				"tf": 0
			}, {
				"id": "LH500",
				"name": "Sitework",
				"duration": 95.0,
				"tf": -53.0
			}, {
				"id": "LH510",
				"name": "Site work II",
				"duration": 45.0,
				"tf": 74.0
			}],
			"cnt": 78,
			"pct": 0.9873417721518988
		},
		"slippage": {
			"activities": [{
				"id": "LH960",
				"name": "Punch List",
				"early_finish": "2008-04-28 17:00:00",
				"planned_finish": "2008-04-30 17:00:00"
			}, {
				"id": "LH400",
				"name": "Design Building Addition",
				"early_finish": "2007-07-01 00:00:00",
				"planned_finish": "2007-04-04 17:00:00"
			}, {
				"id": "LH469",
				"name": "Assemble Technical Data for Heat Pump",
				"early_finish": "2007-07-01 00:00:00",
				"planned_finish": "2007-04-20 17:00:00"
			}, {
				"id": "LH470",
				"name": "Review Technical Data on Heat Pumps",
				"early_finish": "2007-07-01 00:00:00",
				"planned_finish": "2007-05-02 17:00:00"
			}, {
				"id": "LH501",
				"name": "Review and Approve Designs",
				"early_finish": "2007-07-01 00:00:00",
				"planned_finish": "2007-04-17 17:00:00"
			}, {
				"id": "LH555",
				"name": "Foundation",
				"early_finish": "2007-07-18 17:00:00",
				"planned_finish": "2007-07-16 17:00:00"
			}, {
				"id": "LH407",
				"name": "Prepare and Solicit Bids for Flooring",
				"early_finish": "2007-07-01 00:00:00",
				"planned_finish": "2007-05-18 17:00:00"
			}, {
				"id": "LH408",
				"name": "Review Bids for Flooring",
				"early_finish": "2007-07-01 00:00:00",
				"planned_finish": "2007-05-23 17:00:00"
			}, {
				"id": "LH409",
				"name": "Award Contract for Flooring",
				"early_finish": "2007-07-01 00:00:00",
				"planned_finish": "2007-05-24 17:00:00"
			}, {
				"id": "LH411",
				"name": "Prepare and Solicit Bids for Heat Pump",
				"early_finish": "2007-07-01 00:00:00",
				"planned_finish": "2007-05-16 17:00:00"
			}, {
				"id": "LH412",
				"name": "Review Bids for Heat Pump",
				"early_finish": "2007-07-01 00:00:00",
				"planned_finish": "2007-05-18 17:00:00"
			}, {
				"id": "LH413",
				"name": "Award Contract for Heat Pump",
				"early_finish": "2007-07-01 00:00:00",
				"planned_finish": "2007-06-01 17:00:00"
			}, {
				"id": "LH421",
				"name": "Review Bids",
				"early_finish": "2007-07-01 00:00:00",
				"planned_finish": "2007-05-18 17:00:00"
			}, {
				"id": "LH422",
				"name": "Review Bids for Brick",
				"early_finish": "2007-07-01 00:00:00",
				"planned_finish": "2007-05-23 17:00:00"
			}, {
				"id": "LH423",
				"name": "Award Contract for Brick",
				"early_finish": "2007-07-01 00:00:00",
				"planned_finish": "2007-05-25 17:00:00"
			}, {
				"id": "LH450",
				"name": "Assemble Brick Samples",
				"early_finish": "2007-07-01 00:00:00",
				"planned_finish": "2007-04-20 17:00:00"
			}, {
				"id": "LH480",
				"name": "Assemble and Submit Flooring Samples",
				"early_finish": "2007-07-01 00:00:00",
				"planned_finish": "2007-04-27 17:00:00"
			}, {
				"id": "LH560",
				"name": "Review and Approve Flooring",
				"early_finish": "2007-07-01 00:00:00",
				"planned_finish": "2007-05-11 17:00:00"
			}, {
				"id": "LH630",
				"name": "Begin Building Construction",
				"early_finish": "2007-07-01 00:00:00",
				"planned_finish": "2007-04-18 08:00:00"
			}, {
				"id": "LH640",
				"name": "Site Preparation",
				"early_finish": "2007-07-01 00:00:00",
				"planned_finish": "2007-05-01 17:00:00"
			}, {
				"id": "LH650",
				"name": "Excavation",
				"early_finish": "2007-07-01 00:00:00",
				"planned_finish": "2007-05-15 17:00:00"
			}, {
				"id": "LH660",
				"name": "Install Underground Water Lines",
				"early_finish": "2007-07-01 00:00:00",
				"planned_finish": "2007-05-15 17:00:00"
			}, {
				"id": "LH670",
				"name": "Install Storm water lines",
				"early_finish": "2007-07-01 00:00:00",
				"planned_finish": "2007-05-22 17:00:00"
			}, {
				"id": "LH680",
				"name": "Form/Pour Concrete Footings",
				"early_finish": "2007-07-01 00:00:00",
				"planned_finish": "2007-06-05 17:00:00"
			}, {
				"id": "LH681",
				"name": "Concrete Foundation Walls",
				"early_finish": "2007-07-01 00:00:00",
				"planned_finish": "2007-06-25 17:00:00"
			}, {
				"id": "LH690",
				"name": "Form and Pour Slab",
				"early_finish": "2007-07-11 17:00:00",
				"planned_finish": "2007-07-09 17:00:00"
			}, {
				"id": "LH701",
				"name": "Foundation Phase Complete",
				"early_finish": "2007-07-18 17:00:00",
				"planned_finish": "2007-07-16 17:00:00"
			}, {
				"id": "LH490",
				"name": "Site work I",
				"early_finish": "2007-07-01 00:00:00",
				"planned_finish": "2007-06-26 17:00:00"
			}],
			"cnt": 28,
			"pct": 0.35443037974683544
		},
		"critical": {
			"activities": [{
				"id": "LH555",
				"name": "Foundation",
				"duration": 64.0,
				"tf": -53.0
			}, {
				"id": "LH605",
				"name": "Structure",
				"duration": 103.0,
				"tf": 0
			}, {
				"id": "LH750",
				"name": "Elevator",
				"duration": 60.0,
				"tf": -78.0
			}, {
				"id": "LH690",
				"name": "Form and Pour Slab",
				"duration": 10.0,
				"tf": 0
			}, {
				"id": "LH700",
				"name": "Backfill and Compact Walls",
				"duration": 5.0,
				"tf": 0
			}, {
				"id": "LH712",
				"name": "Floor Decking",
				"duration": 28.0,
				"tf": 0
			}, {
				"id": "LH720",
				"name": "Erect Stairwell and Elevator Walls",
				"duration": 10.0,
				"tf": 0
			}, {
				"id": "LH730",
				"name": "Concrete First Floor",
				"duration": 60.0,
				"tf": 0
			}, {
				"id": "LH810",
				"name": "Set Mechanical and Electrical Equipment",
				"duration": 15.0,
				"tf": 0
			}, {
				"id": "LH820",
				"name": "Install HVAC Ducts",
				"duration": 25.0,
				"tf": 0
			}, {
				"id": "LH840",
				"name": "Rough-In Plumbing/Piping",
				"duration": 45.0,
				"tf": 0
			}, {
				"id": "LH855",
				"name": "Install Wiring and Cable",
				"duration": 45.0,
				"tf": 0
			}, {
				"id": "LH860",
				"name": "Install Elevator Rails and Equipment",
				"duration": 40.0,
				"tf": -78.0
			}, {
				"id": "LH870",
				"name": "Connect Equipment",
				"duration": 3.0,
				"tf": 0
			}, {
				"id": "LH871",
				"name": "Startup and Test HVAC",
				"duration": 1.0,
				"tf": 0
			}, {
				"id": "LH890",
				"name": "Drywall in Offices",
				"duration": 15.0,
				"tf": 0
			}, {
				"id": "LH900",
				"name": "Install Ceiling Grid",
				"duration": 15.0,
				"tf": 0
			}, {
				"id": "LH910",
				"name": "Install Floor and Carpeting",
				"duration": 5.0,
				"tf": 0
			}, {
				"id": "LH911",
				"name": "Finish Carpentry and Millwork",
				"duration": 5.0,
				"tf": 0
			}, {
				"id": "LH940",
				"name": "Touch-up and Clean-up",
				"duration": 1.0,
				"tf": 0
			}, {
				"id": "LH941",
				"name": "Test and Balance HVAC Equipment",
				"duration": 1.0,
				"tf": 0
			}, {
				"id": "LH735",
				"name": "Concrete Second Floor",
				"duration": 15.0,
				"tf": 0
			}, {
				"id": "LH800",
				"name": "HVAC, Plumbing & Fire Protection",
				"duration": 115.0,
				"tf": 0
			}, {
				"id": "LH850",
				"name": "Electrical Costs",
				"duration": 152.0,
				"tf": 0
			}, {
				"id": "LH655",
				"name": "Exterior Finish Costs",
				"duration": 205.0,
				"tf": -27.0
			}, {
				"id": "LH705",
				"name": "Interior Finish Costs",
				"duration": 64.0,
				"tf": 0
			}, {
				"id": "LH500",
				"name": "Sitework",
				"duration": 95.0,
				"tf": -53.0
			}],
			"cnt": 27,
			"pct": 0.34177215189873417
		}
	}
}`

**Comment by enginance** [comment]
That is much appreciated @HassanEmam, however I still get error types as follows with the same "Sample Xer 01" file.
I tried to run the test.py file from your new code.

Traceback (most recent call last):
  File "c:/Users/XXX/VisualStudio Projects/PyP6Xer-master trial/test_trial.py", line 204, in <module>
    print(health.analysis())
  File "c:\Users\XXX\VisualStudio Projects\PyP6Xer-master trial\xerparser\dcma14\analysis.py", line 119, in analysis
    self.invalidactualstart = list(filter(lambda x: None if x.act_start_date is None else x.act_start_date > data_date[str(x.proj_id)], self.programme.activities.activities))
  File "c:\Users\XXX\VisualStudio Projects\PyP6Xer-master trial\xerparser\dcma14\analysis.py", line 119, in <lambda>
    self.invalidactualstart = list(filter(lambda x: None if x.act_start_date is None else x.act_start_date > data_date[str(x.proj_id)], self.programme.activities.activities))
KeyError: '2812'
PS C:\Users\XXX\VisualStudio Projects\PyP6Xer-master trial>

**Comment by HassanEmam** [comment]
Thanks @enginance for the feedback
Unfortunately, I cannot replicate the error on my machine as everything seems to work fine - see image below
I would suggest to perhaps update the package if you installed it with pip
Otherwise, you can share the code you are using causing the error

![image](https://user-images.githubusercontent.com/6377734/154004753-6b346876-489a-4399-a086-bd6350f079a5.png)

**Comment by enginance** [comment]
Many thanks @HassanEmam, it looks like the error occours when I reach the DCMA health check 
health = DCMA14(r)
print(health.analysis())

And another error is in module analysis in row 119. Please see screenshot below.

![image](https://user-images.githubusercontent.com/90355826/154029861-3a2ef766-be8f-4408-9912-2d0e4f80d35c.png)

**Comment by enginance** [comment]
Hi @HassanEmam, unfortunately it looks like the HEALTH ANALYSIS returns an error. Could you please advise if this is an issue in the code?

Specifically at line 205 of the test.py:

health = DCMA14(r)
print(health.analysis())

![image](https://user-images.githubusercontent.com/90355826/156070259-8414fc70-da31-4807-b7a2-2c5b7b1a8c18.png)

**Comment by HassanEmam** [comment]
@enginance 
Unfortunately I cannot replicate the error. Could you zip the whole folder and send it to me so I can investigate it.

**Comment by enginance** [comment]
Thanks for your prompt support @HassanEmam , please find herein attached the ZIP folder. The trial file I'm running and getting errors with is "test_trial.py"
[PyP6Xer-master trial.zip](https://github.com/HassanEmam/PyP6Xer/files/8160618/PyP6Xer-master.trial.zip)

**Comment by HassanEmam** [comment]
Not sure what is there in your file; I can have a look at it later. However, in the test file I have changed the filename and it seems to be working. I have attached the amended file.


[test.zip](https://github.com/HassanEmam/PyP6Xer/files/8160699/test.zip)
.

**Comment by enginance** [comment]
@HassanEmam yes! It's working properly now, many thanks!

I've found that, for some reasons, the code I've added at the top of the test_trial file was causing issues. I paste the code here FYI.
Thanks a lot!

##################################################################################################
# Print all projects in the file
print("****************** PROJECTS ******************")
for project in r.projects:
    print(project.proj_short_name, dir(project))

##################################################################################################
# Print all WBS in the file
print("****************** WBS ******************")
for wbs in r.wbss:
    print(wbs.wbs_id, wbs.wbs_name, "Parent: ", wbs.parent_wbs_id)

##################################################################################################
# Print all activities in the file
print("****************** TASKS ******************")
for activity in r.activities:
    print(activity.task_name, "WBS_ID: ", activity.wbs_id)

**Comment by HassanEmam** [comment]
I hope this has resolved your issues; I will mark this as closed for the time being.

**Comment by HassanEmam** [comment]
@mkhussien 

Could you please share details on the error message you are getting

**Comment by mkhussien** [comment]
I'm not getting any errors; the file is executing normally but I'm not getting any output either

**Comment by mkhussien** [comment]
![Capture](https://user-images.githubusercontent.com/101322569/197767150-cd49c459-fc17-4502-9db5-6b95e2a6a588.JPG)

**Comment by HassanEmam** [comment]
OK do you have a file sample.xer in the same folder as test.py

https://github.com/HassanEmam/PyP6Xer/blob/194f3964815e51e8114597bc8c4193e85c00d4c6/test.py#L10

**Comment by mkhussien** [comment]
Yes

**Comment by mkhussien** [comment]
[test file.zip](https://github.com/HassanEmam/PyP6Xer/files/9860208/test.file.zip)

I have attached the sample test script

**Comment by mkhussien** [comment]
@HassanEmam I manged to get it working fine now.
